name: Pac-Man Commit Animation

on:
  push:
    branches:
      - main

jobs:
  generate-pacman-animation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Generate Pac-Man SVG
      run: |
        # Criar um arquivo SVG do Pac-Man
        echo '<?xml version="1.0" encoding="UTF-8"?>' > pacman_animation.svg
        echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" width="200" height="200">' >> pacman_animation.svg
        echo '<circle cx="100" cy="100" r="80" fill="yellow" />' >> pacman_animation.svg
        echo '<polygon points="100,100 180,50 180,150" fill="black" />' >> pacman_animation.svg
        echo '</svg>' >> pacman_animation.svg

    - name: Commit and push generated Pac-Man SVG
      run: |
        git add pacman_animation.svg
        git commit -m "Update Pac-Man animation"
        git push
